-- CreateTable
CREATE TABLE "Grades" (
    "id" INTEGER NOT NULL DEFAULT 1,
    "kG" INTEGER NOT NULL DEFAULT 0,
    "from1Ton4" INTEGER NOT NULL DEFAULT 0,
    "from5To6" INTEGER NOT NULL DEFAULT 0,
    "from7To8" INTEGER NOT NULL DEFAULT 0,
    "from9To10" INTEGER NOT NULL DEFAULT 0,
    "from11T012" INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT "Grades_pkey" PRIMARY KEY ("id")
);
